// Generated by CoffeeScript 1.8.0
var app, cmd, cors, exec, express, http, returnAirsensorData;

cors = require('cors');

express = require('express');

app = express();

http = require('http').Server(app);

app.use(cors());

exec = require('child_process').exec;

cmd = "/home/pi/airsensor/airsensor -o -j";

returnAirsensorData = function(res) {
  console.log("Getting getAirsensorData");
  return exec(cmd, function(error, stdout, stderr) {
    console.log(stdout);
    res.setHeader('Content-Type', 'application/json');
    return res.send(stdout);
  });
};

app.get('/', function(req, res) {
  return returnAirsensorData(res);
});

http.listen(3001, function() {
  return console.log('listening on *:3001');
});
