// Generated by CoffeeScript 1.8.0
angular.module('clock').factory('AirsensorFactory', function() {
  var qualityIndex, streamAirsensor;
  Number.prototype.map = function(in_min, in_max, out_min, out_max) {
    return parseInt((this - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
  };
  streamAirsensor = function(callback) {
    var airstream;
    if (typeof EventSource === "undefined") {
      return steroids.logger.log("EventSource not supported!");
    } else {
      airstream = new EventSource('http://192.168.0.18:3001/stream');
      return airstream.onmessage = function(message) {
        return callback(qualityIndex(JSON.parse(message.data)));
      };
    }
  };
  qualityIndex = function(data) {
    var hslHue, index, voc;
    voc = parseInt(data.e[0].v);
    hslHue = voc.map(450, 2000, 120, 0);
    index = voc.map(450, 2000, 100, 0);
    return {
      hsl: hslHue,
      index: index
    };
  };
  return {
    streamAirsensor: streamAirsensor
  };
});
