// Generated by CoffeeScript 1.8.0
angular.module('clock').factory('AirsensorFactory', [
  '$interval', '$http', function($interval, $http) {
    var cachedForecast, currentAirvalues, interval, pollAirsensor, qualityIndex;
    interval = 1000 * 60;
    cachedForecast = null;
    Number.prototype.map = function(in_min, in_max, out_min, out_max) {
      return parseInt((this - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
    };
    pollAirsensor = function(callback) {
      var url;
      steroids.logger.log("polling AirsensorFactory");
      url = 'http://192.168.0.18:3001/';
      return $http.get(url).then(function(data) {
        return callback(null, data);
      }, function(error) {
        steroids.logger.error(error);
        return callback(error);
      });
    };
    qualityIndex = function(callback) {
      return currentAirvalues(function(err, data) {
        var hslHue, index, voc;
        voc = parseInt(data.data.e[0].v);
        hslHue = voc.map(450, 2000, 120, 0);
        index = voc.map(450, 2000, 100, 0);
        return callback(null, {
          hsl: hslHue,
          index: index
        });
      });
    };
    currentAirvalues = function(callback) {
      if (!cachedForecast) {
        return pollAirsensor(function(err, data) {
          cachedForecast = data;
          return callback(null, cachedForecast);
        });
      } else {
        return callback(null, cachedForecast);
      }
    };
    $interval(function() {
      return pollAirsensor(function(err, data) {
        return cachedForecast = data;
      });
    }, interval);
    return {
      currentAirvalues: currentAirvalues,
      qualityIndex: qualityIndex
    };
  }
]);
