// Generated by CoffeeScript 1.8.0
angular.module('clock').service('ClockService', [
  '$interval', function($interval) {
    moment.locale('de');
    this.getTime = function() {
      return moment().format("HH:mm");
    };
    this.getDate = function() {
      return moment().format("dddd, D. MMMM");
    };
  }
]);
