// Generated by CoffeeScript 1.10.0
var Dimmer, _, range;

_ = require('underscore');

Number.prototype.mapFloat = function(in_min, in_max, out_min, out_max) {
  return parseFloat((this - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
};

range = [22, 6];

Dimmer = {
  norm_range: function() {
    var end, offset, start;
    offset = Math.abs(range[0] - 24);
    start = range[0] + offset - 24;
    end = range.pop() + offset;
    return {
      start: start,
      end: end,
      offset: offset
    };
  },
  dim: function(time) {
    var norm_range, norm_time1, norm_time2, off_time;
    norm_range = Dimmer.norm_range();
    off_time = time + norm_range.offset;
    off_time = off_time >= 24 ? off_time - 24 : off_time;
    norm_time1 = off_time.mapFloat(norm_range.start, norm_range.end, 1.0, .0);
    norm_time2 = off_time.mapFloat(norm_range.start, norm_range.end, .0, 1.0);
    return Math.min(1, Math.max(norm_time1, norm_time2));
  }
};

module.exports = Dimmer;
