// Generated by CoffeeScript 1.8.0
module.exports = {
  app: {
    name: "SqueezeBoard2"
  },
  webView: {
    viewsIgnoreStatusBar: false,
    enableDoubleTapToFocus: false,
    disableOverscroll: false,
    enableViewportScale: false,
    enablePopGestureRecognition: true,
    allowInlineMediaPlayback: true
  },
  statusBar: {
    enabled: false,
    style: "default"
  }
};
