// Generated by CoffeeScript 1.10.0
jest.dontMock('../app/clock/scripts/dim');

jest.dontMock('underscore');

describe('dim', function() {
  it('dims to 1 at 22:00', function() {
    var Dimmer;
    Dimmer = require('../app/clock/scripts/dim');
    return expect(Dimmer.dim(22)).toBe(1);
  });
  it('dims to .5 at 02:00', function() {
    var Dimmer;
    Dimmer = require('../app/clock/scripts/dim');
    return expect(Dimmer.dim(2)).toBe(.5);
  });
  it('dims to 1 at 6:00', function() {
    var Dimmer;
    Dimmer = require('../app/clock/scripts/dim');
    return expect(Dimmer.dim(6)).toBe(1);
  });
  return it('dims to 1 at 14:00', function() {
    var Dimmer;
    Dimmer = require('../app/clock/scripts/dim');
    return expect(Dimmer.dim(14)).toBe(1);
  });
});
